// topics/data.js

export const TOPICS = [
  {
    id: 1,
    title: 'React Basics',
    questions: 36,
    progress: 90,
    status: 'In Progress',
    color: 'from-green-400 to-emerald-500',
    iconBg: 'bg-green-500',
    progressColor: 'bg-green-400',
  },
  {
    id: 2,
    title: 'React Hooks',
    questions: 28,
    progress: 68,
    status: 'In Progress',
    color: 'from-indigo-400 to-purple-500',
    iconBg: 'bg-indigo-500',
    progressColor: 'bg-indigo-500',
  },
  {
    id: 3,
    title: 'Redux',
    questions: 22,
    progress: 45,
    status: 'In Progress',
    color: 'from-yellow-400 to-orange-500',
    iconBg: 'bg-yellow-500',
    progressColor: 'bg-yellow-400',
  },
  {
    id: 4,
    title: 'Next.js',
    questions: 30,
    progress: 30,
    status: 'In Progress',
    color: 'from-cyan-400 to-blue-500',
    iconBg: 'bg-cyan-500',
    progressColor: 'bg-cyan-400',
  },
  {
    id: 5,
    title: 'Advanced React',
    questions: 40,
    progress: 20,
    status: 'In Progress',
    color: 'from-red-400 to-rose-500',
    iconBg: 'bg-red-500',
    progressColor: 'bg-red-400',
  },
  {
    id: 6,
    title: 'Performance',
    questions: 18,
    progress: 0,
    status: 'Not Started',
    color: 'from-teal-400 to-green-500',
    iconBg: 'bg-teal-500',
    progressColor: 'bg-teal-400',
  },
  {
    id: 7,
    title: 'Testing',
    questions: 24,
    progress: 0,
    status: 'Not Started',
    color: 'from-pink-400 to-rose-500',
    iconBg: 'bg-pink-500',
    progressColor: 'bg-pink-400',
  },
  {
    id: 8,
    title: 'React Router',
    questions: 16,
    progress: 0,
    status: 'Not Started',
    color: 'from-violet-400 to-purple-500',
    iconBg: 'bg-violet-500',
    progressColor: 'bg-violet-400',
  },
  {
    id: 9,
    title: 'TypeScript + React',
    questions: 50,
    progress: 0,
    status: 'Not Started',
    color: 'from-sky-400 to-blue-500',
    iconBg: 'bg-sky-500',
    progressColor: 'bg-sky-400',
  },
];

export const TOPIC_FILTERS = ['All Topics', 'In Progress', 'Completed', 'Not Started'];
